GRANT ALL ON WAREHOUSE compute_wh TO ROLE sysadmin;
USE ROLE sysadmin;
-- Create a 3-tiered database structure : RAW, STG, PRD

CREATE DATABASE raw;
CREATE DATABASE stg;
CREATE DATABASE prd;

-- Create 3 users and assign (custom) roles :
 
-- BI_user:
-- The BI_role
-- Can query the STG and PRD database

CREAT USER bi_user
    PASSWORD='abc123' 
    DEFAULT_SECONDARY_ROLES = ('ALL') 
    MUST_CHANGE_PASSWORD = TRUE;

CREATE ROLE bi_role; -- as account admin i guess!
GRANT ROLE bi_role TO USER bi_user;
GRANT ROLE bi_role to ROLE sysadmin;

GRANT USAGE ON DATABASE stg TO ROLE bi_role;
GRANT USAGE ON ALL SCHEMAS IN DATABASE stg TO ROLE bi_role;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE stg TO ROLE bi_role;
GRANT SELECT ON ALL TABLES IN DATABASE stg TO ROLE bi_role;
GRANT SELECT ON FUTURE TABLES IN DATABASE stg TO ROLE bi_role;

GRANT USAGE ON DATABASE prd TO ROLE bi_role;
GRANT USAGE ON ALL SCHEMAS IN DATABASE prd TO ROLE bi_role;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE prd TO ROLE bi_role;
GRANT SELECT ON ALL TABLES IN DATABASE prd TO ROLE bi_role;
GRANT SELECT ON FUTURE TABLES IN DATABASE prd TO ROLE bi_role;

-- Nimbus_user
-- The sysadmin role
-- Full control over the account
CREATE USER nimbus_user
    PASSWORD='abc123' 
    DEFAULT_SECONDARY_ROLES = ('ALL') 
    MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE sysadmin TO USER nimbus_user;
-- Client_user
-- The Public role
-- Can only query the PRD database

CREATE USER client_user
    PASSWORD='abc123' 
    MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE public TO USER client_user;

GRANT USAGE ON DATABASE prd TO ROLE public;
GRANT USAGE ON ALL SCHEMAS IN DATABASE prd TO ROLE public;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE prd TO ROLE public;
GRANT SELECT ON ALL TABLES IN DATABASE prd TO ROLE public;
GRANT SELECT ON FUTURE TABLES IN DATABASE prd TO ROLE public;

-- Create 2 warehouses:
 
-- General warehouse
-- Usable by everyone
CREATE OR REPLACE WAREHOUSE general_warehouse
    WAREHOUSE_SIZE = XSMALL
    INITIALLY_SUSPENDED = TRUE
    AUTO_SUSPEND = 60;

GRANT USAGE ON WAREHOUSE general_warehouse TO ROLE public;
GRANT OPERATE ON WAREHOUSE general_warehouse TO ROLE sysadmin;

-- Dev warehouse
-- Useable by BI and Nimbus users
DROP warehouse dev_warehouse;

CREATE OR REPLACE WAREHOUSE dev_warehouse
    WAREHOUSE_SIZE = XSMALL
    INITIALLY_SUSPENDED = TRUE
    AUTO_SUSPEND = 60;
    
GRANT USAGE ON WAREHOUSE dev_warehouse TO ROLE bi_role;
GRANT USAGE ON WAREHOUSE dev_warehouse TO ROLE sysadmin;
GRANT OPERATE ON WAREHOUSE dev_warehouse TO ROLE sysadmin;

-- Create a Network policy that gives your current IP access to the account
CREATE NETWORK POLICY net_policy 
    ALLOWED_IP_LIST=('109.116.160.13');
    
-- Using the sample dataset 
-- SNOWFLAKE_SAMPLE_DATA.TPCH_SF1
USE schema snowflake_sample_data.tpch_sf1;

-- Answer the following questions :
-- What is the total revenue generated by all orders in the dataset?
-- revenue = fatturato 
SELECT * FROM orders LIMIT 10;

SELECT 
    SUM(o_totalprice) AS total_revenue
FROM orders;

-- What is the average discount applied to line items in all orders?
SELECT * FROM lineitem LIMIT 10;

SELECT 
    AVG(l_discount) AS avg_discount
FROM lineitem;

-- How many distinct customers have placed orders in the dataset?
SELECT COUNT(*) FROM orders; 
SELECT COUNT(DISTINCT o_custkey) AS distinct_customers FROM orders; 

-- What is the highest price of a part in the inventory?
SELECT
    MAX(p_retailprice) AS highest_part_price
FROM
    part;
    
-- How many orders were placed on a Monday?
SELECT
    o_orderdate
    , DAYOFWEEK(o_orderdate::DATE)
    , DAYNAME(o_orderdate::DATE)
    , MONTHNAME(o_orderdate::DATE)
FROM orders
LIMIT 20;

SELECT
  COUNT(o_orderkey) AS monday_orders
FROM orders
WHERE DAYOFWEEK(o_orderdate::DATE) = 1;


-- Answer the following questions :
-- What is the total revenue generated by all orders in the dataset for the month of January 1993?
SELECT 
    SUM(o_totalprice) AS jan_1993_revenue
FROM orders
WHERE YEAR(o_orderdate::DATE) = 1993 
    AND MONTHNAME(o_orderdate::DATE) = 'Jan';

-- What is the total revenue generated by orders in the dataset where the ship date was after the commit date?
SELECT 
    l_orderkey
    , l_shipdate
    , l_commitdate
    , l_shipmode
FROM lineitem
LIMIT 100;


SELECT 
    SUM(o_totalprice)
FROM (
    -- Get orders that contain a late shipment
    SELECT 
        DISTINCT l_orderkey
        , o_totalprice
    FROM lineitem
    INNER JOIN orders
        ON orders.o_orderkey = lineitem.l_orderkey
    WHERE l_shipdate::DATE > l_commitdate::DATE
);


-- What is the average order size (in terms of total price) for customers from each country?
SELECT 
    n_name AS country_name
    , ROUND(AVG(o_totalprice),2) AS avg_order_size
FROM orders
INNER JOIN customer 
    ON o_custkey = c_custkey
INNER JOIN nation
    ON c_nationkey = n_nationkey
GROUP BY n_name
ORDER BY avg_order_size DESC;

-- What is the average amount of time it takes to ship an order (in days) for each ship mode?
SELECT 
    l_shipmode
    , AVG(DATEDIFF('day', l_commitdate::DATE, l_shipdate::DATE)) AS avg_timetoship
FROM lineitem
GROUP BY l_shipmode
ORDER BY avg_timetoship DESC;

-- What is the average discount applied to line items in orders placed by customers from each region?
SELECT
    n_name AS country_name
    , ROUND(AVG(l_discount), 2) AS avg_discount
FROM lineitem
INNER JOIN orders
    ON o_orderkey = l_orderkey
INNER JOIN customer
    ON o_custkey = c_custkey
INNER JOIN nation
    ON n_nationkey = c_nationkey
GROUP BY country_name
ORDER BY avg_discount DESC;

-- Answer these questions:

-- What is an ERD and what is its purpose in database design?
-- An ERD is an Entity and Relationship Diagram. It is a drawing that represents objects in your database and the relationships between them. Its purpose is to communicate the design of the database to others. In its various model types, it can be used to communicate database design to the businness team, to business analysts, and to the engineers who have to design the database.

-- What is an entity in an ERD?
-- An entity is an object. In an Information Engineering ERD, an entity is any object that contains data. A table, essentially. 
-- In a Cheng style ERD, an entity is a slightly broader concepts that includes things such as attributes as well.

-- What is an attribute in an ERD?
-- An attribute in an ERD is a property that an object can have. 

-- What is a relationship in an ERD?
-- A relationship in an ERD is some kind of verb between objects. 

-- How are cardinality and participation represented in an ERD?
-- In Cheng, cardinality are represented with little 1s and Ms above the relationship lines
-- In IE, they are represented using different line designs. 