-- ON PROVIDER ACCOUNT
USE ROLE accountadmin;

-- CREATE A READER ACCOUNT
CREATE MANAGED ACCOUNT reader_acct1
    ADMIN_NAME = user1, 
    ADMIN_PASSWORD = 'Sdfed43da!44'
    TYPE = READER;

-- ON READER ACCOUNT
-- CREATE CUSTOM ROLES

-- CREATE USERS
CREATE USER user_public
    PASSWORD='abc123' 
    DEFAULT_ROLE = PUBLIC 
    DEFAULT_SECONDARY_ROLES = ('ALL');


-- GRANT ROLES
GRANT ROLE TO USER user_public;


-- CREATE RESOURCE MONITORS
CREATE RESOURCE MONITOR account_limiter WITH CREDIT_QUOTA=10
    notify_users = (user1, user_public)
    TRIGGERS ON 75 PERCENT DO NOTIFY
             ON 90 PERCENT DO SUSPEND
             ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR warehouse_limiter WITH CREDIT_QUOTA=5
    notify_users = (user1, user_public)
    TRIGGERS ON 75 PERCENT DO NOTIFY
             ON 90 PERCENT DO SUSPEND
             ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- CREATE VIRTUAL WAREHOUSES
CREATE WAREHOUSE compute_wh 
    WAREHOUSE_SIZE=XSMALL 
    INITIALLY_SUSPENDED=TRUE
    AUTOSUSPEND=60
    RESOURCE_MONITOR = warehouse_limiter;


-- CREATE A DATABASE FROM EACH SHARE SHARED WITH THE ACCOUNT
create OR REPLACE DATABASE IDENTIFIER('"READER_SHARE"') FROM SHARE IDENTIFIER('MVWAHXC.LC59981."MY_DB_SNOWFLAKE_SECURE_SHARE_1697528714958"');

-- Grant Privileges on DB USING A DB ROLE IF A ROLE HAS BEEN SHARED
GRANT DATABASE ROLE reader_share.dbr TO ROLE PUBLIC;

-- GRANT USAGE ON SHARED DB USING PRIVILEGES GRANTED TO THE SHARE BY THE PROVIDER
GRANT IMPORTED PRIVILEGES ON DATABASE reader_share TO ROLE PUBLIC;

